services:
  servico-pacientes:
    build: .
    container_name: healthsys-servico-pacientes
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - healthsys-network

  postgres:
    image: postgres:16-alpine
    container_name: healthsys-postgres-pacientes
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: pacientes_db
      POSTGRES_USER: healthsys
      POSTGRES_PASSWORD: healthsys
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U healthsys -d pacientes_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - healthsys-network

networks:
  healthsys-network:
    external: true